version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: containers/backend.Dockerfile
    ports:
      - "5011:5011"
    volumes:
      - ./wwwroot:/app/wwwroot
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://0.0.0.0:5011"

  frontend:
    build:
      context: ..
      dockerfile: containers/frontend.Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
