version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: containers/backend.Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./wwwroot:/app/wwwroot
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  frontend:
    build:
      context: ..
      dockerfile: containers/frontend.Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
